struct RenderParams {
  viewport: vec4<f32>,
  counts: vec4<u32>,
};
struct Particle { position: vec2<f32>, velocity: vec2<f32>, mass: f32, brightness: f32, alive: f32, _padding: f32, };
struct Trail { position: vec2<f32>, radius: f32, brightness: f32, created: f32, _padding: vec3<f32>, };
@group(0) @binding(0) var<uniform> params: RenderParams;
@group(0) @binding(1) var<storage, read> particles: array<Particle>;
@group(0) @binding(2) var<storage, read> trails: array<Trail>;
struct VertexOut { @builtin(position) position: vec4<f32>, @location(0) local: vec2<f32>, @location(1) color: vec4<f32>, };
fn corner(v: u32) -> vec2<f32> { if (v == 0u) { return vec2<f32>(-1.0,-1.0); } if (v == 1u) { return vec2<f32>(1.0,-1.0); } if (v == 2u) { return vec2<f32>(-1.0,1.0); } if (v == 3u) { return vec2<f32>(-1.0,1.0); } if (v == 4u) { return vec2<f32>(1.0,-1.0); } return vec2<f32>(1.0,1.0); }
fn clip_position(world: vec2<f32>, size: vec2<f32>) -> vec4<f32> { let pixel = world + params.viewport.xy * 0.5; let center = vec2<f32>(pixel.x / params.viewport.x * 2.0 - 1.0, 1.0 - pixel.y / params.viewport.y * 2.0); let extent = vec2<f32>(size.x / params.viewport.x * 2.0, -size.y / params.viewport.y * 2.0); return vec4<f32>(center + extent, 0.0, 1.0); }
fn transition(f: f32) -> f32 { let p = clamp((f - 0.25) / 0.20, 0.0, 1.0); return p * p * (3.0 - 2.0 * p); }
@vertex fn particle_vertex(@builtin(vertex_index) v: u32, @builtin(instance_index) i: u32) -> VertexOut { let p = particles[i]; if (p.alive < 0.5) { var dead: VertexOut; dead.position = vec4<f32>(2.0, 2.0, 0.0, 1.0); dead.local = vec2<f32>(0.0); dead.color = vec4<f32>(0.0); return dead; } let c = corner(v); let radius = clamp(params.viewport.z * 0.45 * sqrt(p.mass), 0.7, 50.0); let star = transition(p.mass / max(params.viewport.w, 0.0001)); let mb = clamp(sqrt(p.mass / 20.0), 0.0, 1.0); let normal = vec3<f32>(min(p.brightness*.65+mb*.25,1.0), min(p.brightness*.75+mb*.20,1.0), min(p.brightness,1.0)); let body = mix(normal, vec3<f32>(1.0,.72,.15), star); var o: VertexOut; o.position = clip_position(p.position * params.viewport.z, c * radius * 2.7); o.local = c * 2.7; o.color = vec4<f32>(body, .95); return o; }
@fragment fn particle_fragment(i: VertexOut) -> @location(0) vec4<f32> { let p = i.local; let d = length(p); if (d > 2.7) { discard; } let core = smoothstep(1.0, 0.72, d); let glow_outer = smoothstep(2.7, 1.0, d); let glow_inner = smoothstep(1.8, 0.8, d); let star = clamp(i.color.a, 0.0, 1.0); let glow = vec3<f32>(1.0,.45,.05) * .035 * glow_outer + vec3<f32>(1.0,.55,.08) * .08 * glow_inner; let highlight_distance = length(p + vec2<f32>(.25,.25)); let highlight = smoothstep(.55, 0.0, highlight_distance) * vec3<f32>(1.0,.92,.55) * .8; return vec4<f32>(i.color.rgb * core + glow + highlight, max(core * i.color.a, glow.r * star)); }
@vertex fn trail_vertex(@builtin(vertex_index) v: u32, @builtin(instance_index) i: u32) -> VertexOut { let t = trails[i]; let age = max(bitcast<f32>(params.counts.z) - t.created, 0.0); let fade = pow(.5, age / 10.0); let width = clamp(t.radius * params.viewport.z * 2.0, 1.0, 2.0); let c = corner(v); var o: VertexOut; o.position = clip_position(t.position * params.viewport.z, c * width * .5); o.local = c; o.color = vec4<f32>(t.brightness*.60,t.brightness*.75,t.brightness,.35*fade); return o; }
@fragment fn trail_fragment(i: VertexOut) -> @location(0) vec4<f32> { let d=length(i.local); if (d>1.0) { discard; } return vec4<f32>(i.color.rgb, i.color.a * (1.0-smoothstep(.75,1.0,d))); }
